### ISSUE TITLE
raco pollen render doesn't respect omitted-path? (pagetree specifically)

### ISSUE THREAD

**Issue by sorawee** [mbutterick/pollen#189]
I setup `omitted-path?` to omit `.sass-cache`. I confirm that it indeed omits this path for page rendering. However, it doesn't omit this path for pagetree generation.

That is, I still see this line:

```
pollen: rendering generated pagetree for directory /path/to/.sass-cache
```

appearing when I `raco pollen render -s`.

**Comment by mbutterick** [comment]
As the [docs indicate](http://docs.racket-lang.org/pollen/Setup.html#%28def._%28%28lib._pollen%2Fsetup..rkt%29._setup~3aomitted-path~3f%29%29), `omitted-path?` only affects `raco pollen render` and `raco pollen publish`.

I don’t carry this behavior through to automatic pagetrees because that’s what `.ptree` files are for.

**Comment by mbutterick** [comment]
BTW a `.ptree` source can have Pollen commands inside it that generate all or part of the pagetree. IOW it doesn’t have to be a static tree of pagenodes. So if you want to take your `omitted-path?` predicate and apply it to the result of `directory->pagetree`, AFAICT you’ll get the behavior you want.

**Comment by sorawee** [comment]
Alright, that's fair. Closing.
