### ISSUE TITLE
Comparison with Groff/Troff

### ISSUE THREAD

**Issue by DonaldTsang** [mbutterick/pollen#198]
Seen this product as a comparison to Groff's custom markup language, was wondering what are the differences between Groff's *m and Pollen?

**Comment by mbutterick** [comment]
I’ve never used Groff & Troff so I’m afraid I can’t compare them.

**Comment by DonaldTsang** [comment]
@mbutterick https://www.gnu.org/software/groff/manual/html_node/ms.html#ms has a good intro
Also
- https://linux.die.net/man/7/groff_mm
- https://linux.die.net/man/7/groff_me
- https://www.schaffter.ca/mom/mom-01.html

**Comment by mbutterick** [comment]
You might do better to ask on the Pollen mailing list, perhaps someone has experience with Groff and can answer.

**Comment by DonaldTsang** [comment]
Mailing list isn't really that convenient, could you do that on my behalf and dump the results here?

**Comment by mbutterick** [comment]
On reflection, I think Groff would suit you better. Hope that helps!

**Comment by DonaldTsang** [comment]
@mbutterick How so? I think I am missing something here.

**Comment by mbutterick** [comment]
> Mailing list isn't really that convenient

I apologize. I thought you were saying this just to be a difficult person. But if you are in China, I have learned that it is indeed difficult to access Google mailing lists. 

The answer isn’t really different however. I’ve never come across anyone who used Groff. Really the best idea is to try both on some small project, and see which you prefer. I would expect that Racket / Pollen benefits from the 30+ years in computing advances since the golden age of Groff.
