### ISSUE TITLE
Project server shows .pmd but renders .pp

### ISSUE THREAD

**Issue by NPN** [mbutterick/pollen#216]
## Steps to reproduce
* Save the downtown example from the quick tour (or any other `.pmd` file) in a directory as both `downtown.html.pmd` and `downtown.html.pp`.
* Open the project server dashboard. Only `downtown.html.pmd` is shown.
* View the rendered file. It's Markdown source instead of rendered HTML. The server logs confirm: `pollen: rendering /downtown.html.pp`.

The same behavior happens if we replace `downtown.html.pp` with `downtown.html.p`.

## Expected behavior
The rendered file matches the name of file shown in the dashboard. And perhaps all Pollen files are supposed to show in the dashboard?

**Comment by mbutterick** [comment]
No, the project-server dashboard only shows output files. Your test case is mischievous because it creates a deliberate ambiguity: you have multiple source files that produce the same output file. Though I think this deserves to be classified as UDB, I can fix it so that ambiguities are resolved consistently.
