### ISSUE TITLE
general static-site generator

### ISSUE THREAD

**Issue by gour** [mbutterick/pollen#43]
Hello Matthew,

your "Why Lisp? Why Racket?" turned me eventually to learn the language - I bought RoR book yesterday and starting lerning according to my time-constraints.

Considering that I'm atm using [Hugo](http://gohugo.io/) - static site generator written in Go which is very nice and flexible capable to be used not for just blog-only sites like majority of other SSGs I did [ask](https://github.com/greghendershott/frog/issues/123) the author of Frog about his plans to extend it, but he mentioned your project considering he does not plan to change Frog's design.

I'm aware that you're probably more into 'web books' than 'general static site generator', still I'm asking what do you think about that idea and/or whether Pollen could be used/developed for such purpose, iow to build simple blog orriented web sites as well as more general/bigger web sites?

The obvious motivation is, of course, the fact that Markdown is too limited for lartger or more complex docs - I'm awaiting next version of Hugo to bring support for Asciidoc(tor) - while by using Scribble one has lot of power his/her hands.

**Comment by mbutterick** [comment]
Well, in my formulation a web book *is* a static site. Frog has a lot of helpful features for making a blog that Pollen doesn't. (Though I try to take good ideas from @greghendershott whenever I can. For instance I rely on his Markdown parser.)

But in general, the distinguishing feature of Pollen is the programmability. It’s really just a different way of using Racket / Scribble. So if others want to add bloggy features (e.g. entries organized by time), that's great. But since we already have a lot of excellent blogging tools, and I'm not a blogger, I don't foresee pushing Pollen in that direction myself.

**Comment by mbutterick** [comment]
BTW you asked in [the other thread](https://github.com/greghendershott/frog/issues/123) about Taxonomies and Shortcodes in Hugo. Based on a quick look, it seems like these are just fancy names for simple ideas. In Racket, Taxonomies would be data files with a nested list. Shortcodes would be functions. These are exposed in Pollen as [pagetrees](http://pkg-build.racket-lang.org/doc/pollen/Pagetree.html?q=pagetree) and [tag functions](http://pkg-build.racket-lang.org/doc/pollen/third-tutorial.html?q=tag%20function#%28part._.Tags___tag_functions%29). Of course, the Racket / Pollen versions of these ideas are simpler and more flexible, because there’s no separate template language.

**Comment by gour** [comment]
> Well, in my formulation a web book *is* a static site. 

I have nothing against static site, just the contrary. :-)

> Frog has a lot of helpful features for making a blog that Pollen doesn't. 

Well, I *might* use it when there is a need for it...

> But in general, the distinguishing feature of Pollen is the programmability. It’s really just a different way of using Racket / Scribble. 

...but I believe I'm leaning more towards Pollen/Scribble...

> So if others want to add bloggy features (e.g. entries organized by time), that's great. But since we already have a lot of excellent blogging tools, and I'm not a blogger, I don't foresee pushing Pollen in that direction myself.

...and after reading about [The Bomb in the Garden](http://unitscale.com/mb/bomb-in-the-garden/) I'm even more convinced. ;)

Thank you!

**Comment by jbshirk** [comment]
Forgive me for bumping this very old thread, but I have been looking for days to answer the question, "Frog or Pollen?" I started reading about Pollen months ago, and I know I want/need the power it offers. So now my question is, "if I start building with Frog, will I be locked out of all of the power of Pollen?" Sooner or later, someone else will be asking this question.

**Comment by mbutterick** [comment]
I don’t have a better answer than the [one I already posted](https://github.com/mbutterick/pollen/issues/43#issuecomment-89823784). I think this question ought to be reposted on the Racket Slack channel or mailing list. Frog users don’t hang out here.
