### ISSUE TITLE
Asciidoc(tor) support

### ISSUE THREAD

**Issue by gour** [mbutterick/pollen#45]
Hello,

I'm reading 3rd part of tutorial, but wonder if you have any experience with [Asciidoc(tor)](http://asciidoctor.org/) markup which has ability to convert to (industry-standard) DocBook with all XML-related benefits.

In my case of intended usage of AsciiDoc(tor) I'm not thinking about DocBook toolchain, but wonder if you explored such possibility?

Personally, I'm more interested to use Polen/Scribble markup, but considering there is support in Polen for Markdown, Asciidoc(tor) seems interesting option...

**Comment by mbutterick** [comment]
Pollen has Markdown support only because Greg wrote a (Markdown parser)[http://github.com/greghendershott/markdown], and thus it was easy for me to implement. In general, I’m (opposed to)[http://pkg-build.racket-lang.org/doc/pollen/second-tutorial.html#%28part._.Prelude__my_principled_objection_to_.Markdown%29] simplified-markup tools like Markdown because they’re too limiting. This is why I made Pollen: to have a better alternative. If someone wants to use Markdown or Asciidoc, there are plenty of good tools that already exist. 

As for DocBook, same issue — it’s just a question of shaping your output to meet the DocBook schema. It would be no big deal to use Pollen to make DocBook XML (or any XML file).
